### ISSUE TITLE
apktool can't decompile apk

### ISSUE THREAD

**Issue by sneddy781** [oscar0812/java-apk-obfuscator#2]
**Describe the bug**
i managed to make it work but i get this error message (: ...\src\com\oscar0812\obfuscation\MainClass.java:42:18
java: exception java.io.IOException is never thrown in body of corresponding try statement) of apk tool only when i import newer version of apktool, otherwise i get this error : brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)

anyway to fix this ?

normal apktool works perfectly, is there a way to obfuscate only smali, i can recompile via apktool later

**Comment by sneddy781** [comment]
i cleaned cache, changed java sdk from 22 to 17 and get this and it keep going and going 
I: Using Apktool 2.6.0 on mygame.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x0001b53c
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000021
...
and at the end i get

I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000051
I: Loading resource table from file: C:\Users\ferha\AppData\Local\apktool\framework\1.apk
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)

i can max apktool 2.6.0 jar but results are same

**Comment by sneddy781** [comment]
Ok soo i resolved this issue by deleting 1.apk, but strings are not encrypted sadly, can you add string encryption please ?
